/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope & {
  __WB_MANIFEST: Array<{ url: string; revision: string | null }>;
};

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

const CACHE_NAME = 'ist26-offline-v5-networkfirst';

self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => {
      return Promise.all(
        keys.map((key) => {
          if (key !== CACHE_NAME) {
            console.log('[SW] Purging old cache:', key);
            return caches.delete(key);
          }
        })
      );
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  const url = new URL(event.request.url);

  // Network-First for everything: always get the latest code/data if online, fallback to cache if offline
  event.respondWith(
    fetch(event.request)
      .then((response) => {
        if (response && response.status === 200) {
          const toCache = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, toCache));
        }
        return response;
      })
      .catch(async () => {
        // When offline, serve from cache
        const cached = await caches.match(event.request);
        if (cached) return cached;

        if (event.request.mode === 'navigate') {
          const indexCached = (await caches.match('/index.html')) || (await caches.match('./index.html'));
          if (indexCached) return indexCached;
        }

        if (url.pathname.includes('/images/events/')) {
          return new Response('Offline image not available', { status: 503 });
        }

        return new Response('Offline', { status: 503, statusText: 'Offline' });
      })
  );
});
